/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ConstructButton: typeof import('./src/components/Construct/Button.vue')['default']
    ConstructInput: typeof import('./src/components/Construct/Input.vue')['default']
    ConstructInputBox: typeof import('./src/components/Construct/InputBox.vue')['default']
    ConstructLayout: typeof import('./src/components/Construct/Layout.vue')['default']
    ConstructLink: typeof import('./src/components/Construct/Link.vue')['default']
    ConstructPage: typeof import('./src/components/Construct/Page.vue')['default']
    ConstructPillBox: typeof import('./src/components/Construct/PillBox.vue')['default']
    ConstructRadioOption: typeof import('./src/components/Construct/RadioOption.vue')['default']
    ConstructRadioSelect: typeof import('./src/components/Construct/RadioSelect.vue')['default']
    ConstructRequiredMark: typeof import('./src/components/Construct/RequiredMark.vue')['default']
    ConstructSelect: typeof import('./src/components/Construct/Select.vue')['default']
    ConstructTabs: typeof import('./src/components/Construct/Tabs.vue')['default']
    ConstructTextArea: typeof import('./src/components/Construct/TextArea.vue')['default']
    ConstructTitle: typeof import('./src/components/Construct/Title.vue')['default']
  }
}
